# Dataset configuration - all paths are absolute
sampling_rate: 16000

datasets:
  aishell:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_aishell/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_aishell/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_aishell/text"
  
  buckeye:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_buckeye/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_buckeye/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_buckeye/text"
  
  cv:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_cv/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_cv/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_cv/text"
  
  doreco:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_doreco/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_doreco/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_doreco/text"
  
  epadb:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_epadb/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_epadb/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_epadb/text"
  
  fleurs:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_fleurs/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_fleurs/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_fleurs/text"
  
  fleurs_indv:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_fleurs_indv/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_fleurs/text.good" # !!different!!
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_fleurs/text"
  
  kazakh:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_kazakh/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_kazakh/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_kazakh/text"
  
  l2arctic:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_l2arctic/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_l2arctic/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_l2arctic/text"
  
  librispeech:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_librispeech/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_librispeech/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_librispeech/text"
  
  mls_dutch:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_dutch/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_dutch/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_dutch/text"
  
  mls_french:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_french/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_french/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_french/text"
  
  mls_german:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_german/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_german/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_german/text"
  
  mls_italian:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_italian/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_italian/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_italian/text"
  
  mls_polish:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_polish/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_polish/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_polish/text"
  
  mls_portuguese:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_portuguese/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_portuguese/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_portuguese/text"
  
  mls_spanish:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_spanish/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_spanish/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_mls_spanish/text"
  
  southengland:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_southengland/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_southengland/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_southengland/text"
  
  speechoceannotth:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_speechoceannotth/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_speechoceannotth/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_speechoceannotth/text"
  
  tamil:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_tamil/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_tamil/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_tamil/text"
  
  tusom2021:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_tusom2021/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_tusom2021/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_tusom2021/text"
  
  voxangeles:
    wav_scp: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_voxangeles/wav.scp"
    text_phoneme: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_voxangeles/text.good"
    language: "/work/hdd/bbjs/shared/powsm/s2t1/dump/raw/test_voxangeles/text"